---
title: "Algorithm benchmarking script"
subtitle: "FINAL REPORT"
date: "`r Sys.Date()`"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: hide
    theme: united
    highlight: tango
author: Anna Guadall
params:
  file: "real_02/real_02_compens_01_1/ff.fcs"
  id: ""
  outliers: 
    label: "0: no outiliers, 1: outliers"
    value: 0
  norm: ""
  tsne: ""    # t-SNE
  umap: ""    # UMAP
---


```{r setup, include=FALSE, cache = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, cache = F)
```

```{r libraries, message=FALSE, cache = FALSE}
#library(caret)
library(cytofkit)
#library(flowMeans) # necessary for count() function!?
#library(umap)
library(knitr)
library(flowCore)
```

# Path
```{r path}
getwd()
```

# Parameters
```{r data}
# import the fcs file
ff <- read.FCS(params$file)
data <- as.data.frame(ff@exprs)

# Import the labels
labels <- readRDS("labels_copy.rds")
#labels <- readRDS("real_02/real_02_compens_01_1/labels")

# number of populations
#n_pops <- length(levels(labels)) - as.numeric(params$outliers)
n_pops <- readRDS("n_pops_copy.rds")
```

```{r freqs}
table_frqs <- readRDS("frequencies_copy.rds")
```

File: ``r params$id``   
``r nrow(data)`` events.  
`r n_pops` populations.  
Outliers (0: NO, 1: YES): `r params$outliers`  
`r ncol(data)` parameters (variables).  
Normalization: `r params$norm`  

# Data
```{r colnames}
# parameters
colnames(data)
```

```{r table freqs}
kable(table_frqs)
```

## Raw data
```{r head}
head(data)
```

```{r boxplot}
summary(data)
par(cex.axis = 0.5)
boxplot(data, las = 2)
```

```{r dotplot 2}
plot(data[,1:5], pch = 20, cex = 0.1)
```

## Normalization (min-max scaling)
```{r norm}
if (params$norm == "y"){
  ff <- readRDS("ff_copy.rds")
  data <- as.data.frame(ff@exprs)
} else {
  cat("Normalization of data has not been requested")
}
```

```{r head norm}
head(data)
```

```{r boxplot norm}
summary(data)
par(cex.axis = 0.5)
boxplot(data, las = 2)
```

```{r dotplot 2 norm}
plot(data[,1:5], pch = 20, cex = 0.1)
```

# Reduction of dimensionality
```{r colors}
coloring <-  c("darkgoldenrod1", "blue4", "blueviolet", "red", "turquoise", 
               "burlywood3", "cadetblue", "chartreuse", "chartreuse4", "chocolate1",
               "plum1", "cornflowerblue", "yellow", "cyan", "blue",
               "darkgrey","khaki1", "deeppink1", "deeppink4", "black", "snow3")
```

## t-SNE
```{r tsne plot, fig.width = 12}
if (params$tsne == "y"){
  tsne_red <- readRDS("tsne_red_copy.rds")
  tsne_df <- cbind(as.data.frame(tsne_red), as.data.frame(labels))
  cytof_clusterPlot(data = tsne_df, xlab = "tsne_1", ylab = "tsne_2", 
                                    point_size = 0.5, labelRepel = F,
                                    cluster = "labels", sampleLabel = FALSE, labelSize = 0, 
                                    title = paste(params$id, " Labels"),
                                    clusterColor = coloring[1:(n_pops + as.numeric(params$outliers))]) 
}
```

## UMAP
```{r decide umap, fig.width = 12, eval = T}
if (params$umap == "y") {
  umap_red <- readRDS("umap_red_copy.rds")
  umap_df <- cbind(as.data.frame(umap_red), as.data.frame(labels))
  cytof_clusterPlot(data = umap_df, xlab = "UMAP_1", ylab = "UMAP_2", 
                                    point_size = 0.5, labelRepel = F,
                                    cluster = "labels", sampleLabel = FALSE, labelSize = 0, 
                                    title = paste(params$id, " Labels"),
                                    clusterColor = coloring[1:(n_pops + as.numeric(params$outliers))])
} else {
  cat("UMAP method has not been requested")
}
```
                                    
# Intermediary reports

```{r}
list.files(pattern = "05_bench.*\\html")
```

# Results
```{r results, cache = FALSE}
summ <- read.table("summary_copy.txt", head = T)
for(i in 8:16){
  summ[,i] <- as.numeric(summ[,i])
}

kable(summ, digits = 3)
```

# Session info
```{r sessioninfo, cache = F}
sessionInfo()
```

